<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Shopping cart additional info
 * @var $block Magento\Checkout\Block\Cart\Item\Renderer
 */
$format = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php
$_item = $block->getItem();
$payment_fee = $_item->getData('payment_fee');
?>
<span>Payment Fee : <?=$format->currency($payment_fee, true, false);?></span>
