<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block Magento\Catalog\Block\Product\View
 */

$format = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>

<?php $_product = $block->getProduct() ?>
<div>
    <li>
        <strong>Shipping Method: </strong>
        <span><?=$_product->getData('shipping_methods')?></span>
    </li>
    <li>
        <strong>Payment Fee: </strong>
        <span><?=$format->currency($_product->getData('payment_fee'), true, false)?></span>
    </li>
</div>

